import{S as u,a as g,i as l}from"./assets/vendor-059667fa.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const w=e=>e.map(({webformatURL:r,largeImageURL:s,tags:a,likes:t,comments:o,views:n,downloads:L})=>`
          <li class="gallery-item">
            <a href="${s}" class="gallery-link">
              <img src="${r}" alt="${a}" class="gallery-img">
            </a>
            <div class="small-content">
              <small class="text-likes">Likes: ${t}</small>
              <small class="text-views">Views: ${n}</small>
              <small class="text-comments">Comments: ${o}</small>
              <small class="text-downloads">Downloads: ${L}</small>
            </div>
          </li>`).join("");new u(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){document.querySelector(".gallery-list").insertAdjacentHTML("beforeend",w(e))}function m(){const e=document.querySelector(".gallery-list");e.innerHTML=""}function h(){document.querySelector(".btn-loader-js").classList.remove("is-hidden")}function f(){document.querySelector(".btn-loader-js").classList.add("is-hidden")}function b(){const e=document.querySelector(".gallery-list"),r=`<p class="end-of-results">We're sorry, but you've reached the end of search results.</p>`;e.insertAdjacentHTML("beforeend",r)}const S="43933435-35fbbd09623d667ed19d4c9fb",q="https://pixabay.com/api/";g.defaults.baseURL=q;async function p(e,r=1,s=20){const a={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s};try{return(await g.get("",{params:a})).data}catch(t){throw new Error(t.response.statusText||"Error fetching data")}}let c=1,i="";const M=document.querySelector(".search-form");document.querySelector(".gallery-list");const d=document.querySelector(".js-loader"),E=document.querySelector(".btn-loader-js");document.addEventListener("DOMContentLoaded",()=>{M.addEventListener("submit",v),E.addEventListener("click",x)});async function v(e){if(e.preventDefault(),i=e.target.elements.keyboardSearch.value.trim(),c=1,i===""){m(),e.target.reset(),l.error({title:"Error",message:"Search query cannot be empty!",position:"topRight",timeout:2e3});return}m(),f(),d.classList.remove("is-hidden");try{const{hits:r,totalHits:s}=await p(i,c);if(r.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3,color:"red"}),d.classList.add("is-hidden");return}y(r);const a=new u(".gallery a",{captionsData:"alt",captionDelay:250});r.length<s&&h()}catch{l.error({title:"Error",message:"Something went wrong, please try again later!",position:"topRight",timeout:2e3})}finally{e.target.reset(),d.classList.add("is-hidden")}}async function x(){c+=1;try{const{hits:e,totalHits:r}=await p(i,c);y(e),document.querySelectorAll(".gallery-list .gallery-item").length>=r?(f(),b()):h();const a=new u(".gallery a",{captionsData:"alt",captionDelay:250});B()}catch{l.error({title:"Error",message:"Something went wrong, please try again later!",position:"topRight",timeout:2e3})}}function B(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
